language: php
php:
  - '7.4'

branches:
  only:
    - master

addons:
  ssh_known_hosts:
    - "$HOST_IP"

before_install:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in .travis/digitalocean_travis_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host ${HOST_IP}\n\tPort ${HOST_PORT}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - php download_and_save.php

script:
  - rsync -az --delete --exclude=".*" ./* ${SSH_USER}@${HOST_IP}:${PUBLISH_PATH}

notifications:
  slack:
    rooms:
      secure: ZYfZFlGzOI9HJPdKn1I58JgAWt0Zbq4KMHuMwv8G+HYfAKOa/X4HuGYnzncSQjBnULxZuU8OxqFEwWUVzGNSHc2qLC5CPgTtHYRUr/lCxWT+xGtZIJJl6rdiWEf7cl/PPFUjJqBL9yyxKA5wNToNRhlhbai7rMpvLk1RutQYVVApzXSyUgDIYpKTty38NsGnJGh9gpSmtpejQ/0FZi9b7SpO2r4RQiZ/UQVUWob8Qlv0QAtD/EdiYlOfMC/43VicGML2NhFiFfH79JZ6GlLBzk2PMz18XhQaHQea8+b0Le+xtgQSev0rcw5c74FPHASObrsLOKgN6oAXO+tv+aiGZJJ7J5KWwnb+D08rVdPI8XYr/RiVDHIuzLZcDAfItBukmUgk3KSASxd7URDZbvf25HjohEYHCNf34RPjBwgYoTkoW1r3smVj2fJQ3HOJz/E4APARprynXaBPFKwOIp7TVUNgD3AsMum6RoIuT4knvU5mfSabT7Q0QRK8NeB8dq19YYU/ZjVq2GYU/DKXG7MqV43sFe/LJJolhRfOWZyX1K6lkngygV8vP9uClx33Ied3DK1qAHFwyPH3kcsMXGb1UoGAmgECH+qgYXtrTlhxyX5w9MvBiIVPTSfrtNT9u4pqztK5ZaUUXtbBxEPCYIYpgfyCrtuW9625r9DgvEOnNbg=
    on_success: change
    on_failure: always
